[project]
name = "urrssi-pixi-demo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Leonardo Pierre <leonardo.m.pierre@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]

[tasks]
example = "python analysis.py"

[dependencies]
scipy = ">=1.14.0,<2"
matplotlib = ">=3.9.1,<4"
spectral = ">=0.23.1,<0.24"
numpy = ">=2.0.1,<3"
