[project]
name = "urrssi-pixi-demo"
version = "0.1.0"
description = "Add a short description here"
authors = ["Leonardo Pierre <leonardo.m.pierre@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64"]

[tasks]

[dependencies]
